FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y \
    apache2 \
    mariadb-server \
    php \
    libapache2-mod-php \
    openjdk-11-jdk \
    maven \
    git \
    ansible \
    nginx \
    python-pip \
    awscli \
    python-boto \
    unzip \
    docker.io

# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip \
    && unzip terraform_1.1.2_linux_amd64.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform_1.1.2_linux_amd64.zip

# Install Jenkins
RUN docker run \
    -u root \
    --rm \
    -d \
    -p 8080:8080 \
    -p 50000:50000 \
    --name jenkins \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $(which docker):/usr/bin/docker \
    -v /home/jenkins_home:/var/jenkins_home \
    -p 80:80 \
    -p 8080:8080 \
    jenkins/jenkins

CMD ["echo", "Jenkins container built successfully"]
