FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y \
    apache2 \
    mariadb-server \
    php \
    libapache2-mod-php \
    openjdk-11-jdk \
    maven \
    git \
    ansible \
    nginx \
    python-pip \
    awscli \
    python-boto \
    unzip \
    docker.io

# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip \
    && unzip terraform_1.1.2_linux_amd64.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform_1.1.2_linux_amd64.zip

# Install Jenkins
RUN docker run \
    -u root \
    --rm \
    -d \
    -p 8080:8080 \
    -p 50000:50000 \
    --name jenkins \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $(which docker):/usr/bin/docker \
    -v /home/jenkins_home:/var/jenkins_home \
    -p 80:80 \
    -p 8080:8080 \
    jenkins/jenkins

CMD ["echo", "Jenkins container built successfully"]


# 
To ensure that ports 80 and 8080 are open in the Docker container, you can specify the port mappings when running the container. Here's an updated version of the Docker run command to include port mappings:

bash
Copy code
docker run \
  -u root \
  --rm \
  -d \
  -p 8080:8080 \
  -p 50000:50000 \
  --name jenkins \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $(which docker):/usr/bin/docker \
  -v /home/jenkins_home:/var/jenkins_home \
  -p 80:80 \
  -p 8080:8080 \
  jenkins/jenkins
As for the Dockerfile to build a Jenkins container based on your Ubuntu script, you can use the following:

Dockerfile
Copy code
FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y \
    apache2 \
    mariadb-server \
    php \
    libapache2-mod-php \
    openjdk-11-jdk \
    maven \
    git \
    ansible \
    nginx \
    python-pip \
    awscli \
    python-boto \
    unzip \
    docker.io

# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip \
    && unzip terraform_1.1.2_linux_amd64.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform_1.1.2_linux_amd64.zip

# Install Jenkins
RUN docker run \
    -u root \
    --rm \
    -d \
    -p 8080:8080 \
    -p 50000:50000 \
    --name jenkins \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $(which docker):/usr/bin/docker \
    -v /home/jenkins_home:/var/jenkins_home \
    -p 80:80 \
    -p 8080:8080 \
    jenkins/jenkins

CMD ["echo", "Jenkins container built successfully"]

# ---------------------------------------------------------------------------Commands to build the image and the container-----------------------------------------
# You can build the Docker image using the following command:

# docker build -t my-jenkins-image .

# And then run the Docker container from the image:

# docker run -d --name my-jenkins-container -p 8080:8080 -p 80:80 my-jenkins-image
